# Generated by Django 4.1.5 on 2023-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MainIngridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_text',
        ),
        migrations.AddField(
            model_name='product',
            name='declaration',
            field=models.ImageField(blank=True, upload_to='products/declarations/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='product',
            name='description_points',
            field=models.ManyToManyField(blank=True, to='shop.descriptionpoints'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_table',
            field=models.ManyToManyField(blank=True, to='shop.mainingridients'),
        ),
    ]
