# Generated by Django 4.1.5 on 2023-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
