# Generated by Django 4.1.5 on 2023-02-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
