# Generated by Django 4.1.5 on 2023-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_comment_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='method_of_payment',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
