# Generated by Django 4.1.5 on 2023-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_method_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('0', 'До пункта самовывоза СДЭК')], default=None, max_length=31),
        ),
    ]
