# Generated by Django 4.1.5 on 2023-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_of_PVZ',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
